### ISSUE TITLE
Make a readme!

### ISSUE THREAD

**Issue by malakai97** [ToadKing/ddhack#1]
Not sure where to put these files or if I should run the python script.

**Comment by thorsummoner** [comment]
+1, Installation instructions and a proper release like v0.1.0-alpha would be greaaaaat. :boom:

**Comment by rustinlee** [comment]
Basically, you just drop the compiled dlls from the downloads section into the same folder as the game executable and the game will load the modified dlls from there instead of from System32. The python script and source are there if you want to build it yourself but rct2-ddhack2.zip from https://github.com/ToadKing/ddhack/downloads has everything you need and works for RCT2 and Locomotion.
